[package]
name = "slop-analyze"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
petgraph = { workspace = true }
slop-graph = { workspace = true }
slop-parse = { workspace = true }
slop-resolve = { workspace = true }
